name: Application Pipeline 

on:
  push:
    branches:
      - main


jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Cache 
      uses: actions/cache@v2
    - name: Setup env
      uses: actions/setup-python@v2
      with:
        python-version '3.x'
    - name: Check version
      run: python --version
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
    - name: Run Tests
      run: python manage.py test
