image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: 188.148.171.29

stages:
  - build

before_script:
  - whoami
  - rvm "Defaults        env_askpass=/usr/bin/askpass" >> /usr/bin/askpass
  - rvm usermod -aG docker gitlab-runner 
 # - systemctl status docker
  #- systemctl start docker
 # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  image: python:3.8
  script:
    - echo "export OPENSSL_DIR=/usr/lib/ssl/include" >> ~/.bashrc
    - source ~/.bashrc
    - cd ./webservice
    - pip3 install -r requirements.txt
    - python3 manage.py migrate
    - python3 manage.py collectstatic
    - python3 manage.py test
  #only:
   # - master
