image: alpine:latest

variables:
  DJANGO_SETTINGS_MODULE: myproject.settings
  PYTHONPATH: $CI_PROJECT_DIR
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .pip_cache/

stages:
  - test
  - build
#  - deploy

install_dependencies_&_test:
  stage: test
  script:
    - cd ./webservice
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - ssh gitlab-runner -t "sudo apt-get install"
    - sudo apt-get install pkg-config
    - pip3 install -r requirements.txt
    - python3 manage.py test

build_image:
  stage: build
  script:
    - docker build -t app .

#deploy:
 # stage: deploy
 # script:
  #  - docker push myproject
