image: ubuntu-latest

stages:
  - build
  - test

setup:
  stage: build
  script:
    - ssh -t gitlab-runner "sudo ./binary"
    - sudo usermod -a -G sudo gitlab-runner
    - apt-get install python3
    - python --version
    - cd ./webservice
    - pip3 install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate

unit-test:
  stage: test
  script:
    - python3 manage.py test

