image: docker:20

services:
  - docker:20-dind

stages:
  - build
  - test
  - deploy

build-and-test:
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
  only:
    - main
  tags:
    - docker-build
  stage: build
  variables:
    DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$DOCKER_TAG -f docker/Dockerfile . # test happens inside the build process
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  only:
    - main
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  tags:
    - docker-build
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CI_DEPLOY_AGENT
    - kubectl get pods
    - kubectl delete deployment nginx-1
    - kubectl apply -f ./kubernetes/deployment.yaml


