image: alpine:latest

variables:
  DJANGO_SETTINGS_MODULE: myproject.settings
  PYTHONPATH: $CI_PROJECT_DIR
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .pip_cache/

stages:
  - test
  - build
#  - deploy

install_dependencies_&_test:
  stage: test
  script:
   # - DEBIAN_FRONTEND="noninteractive" TZ="Europe/Warsaw" apt-get install tzdata -y
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - cd ./webservice
    - pip3 install --user tokenizers
    - apk add pkgconfig openssl-dev    
    - pip3 install -r requirements.txt
    - python3 manage.py test

build_image:
  stage: build
  script:
    - docker build -t app .

#deploy:
 # stage: deploy
 # script:
  #  - docker push myproject
