image: docker:latest

services:
  - docker:dind
# $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - echo $CI_REGISTRY_USER
  - echo $CI_REGISTRY
stages:
  - build
  - test
  - deploy
# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  script:
    - docker build -t registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection .
    - docker images
   # - docker tag app:latest git.chalmers.se/courses/dit825/2022/group03
    - docker push registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection
    #- docker push app:latest
    # - docker run -t app:latest /bin/bash
    
    - exit

deploy:
  stage: deploy
  tags:
    - docker-build
  image: registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection
  script:
    - kubectl apply -f kubernetes/config/deployment.yml

#deploy:
 # stage: deploy
  #script:
   # - docker pull registry.gitlab.com/<namespace>/<project-name>:latest
    #- docker run -it -d -p 8000:8000 registry.gitlab.com/<namespace>/<project-name>:latest
