image: ubuntu-latest

stages:
  - build
  - test

setup:
  stage: build
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
#    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
#    - echo "${ID_RSA}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - sudo chmod 755 /etc/sudoers
    - 'echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
    - sudo usermod -a -G sudo root
    - apt-get install python3
    - python --version
    - cd ./webservice
    - pip3 install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate

unit-test:
  stage: test
  script:
    - python3 manage.py test

