image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  image: python:3.8
  script:
    - cd ./webservices
    - pip3 install -r requirements.txt
    - python3 manage.py migrate
    - python3 manage.py collectstatic
    - python3 manage.py test
  artifacts:
    paths:
      - ./app/static/
  #only:
   # - master
