
image: python:3.8

variables:
  DJANGO_SETTINGS_MODULE: main.settings
  PYTHONPATH: $CI_PROJECT_DIR
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .pip_cache/

stages:
  - test
  - build
  - deploy

install_dependencies:
  stage: test
  script:
    - pip install -r requirements.txt

run_migrations:
  stage: test
  script:
    - python manage.py makemigrations
    - python manage.py migrate

run_tests:
  stage: test
  script:
    - python manage.py test
