image: docker:latest

services:
  - docker:dind

#before_script:
 # - docker login registry.gitlab.com/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags: 
    - docker-build
  script:
    - docker build -t app:latest .
    #- docker push app:latest

test:
  stage: test
  script:
   # - docker pull app:latest
    - docker run -it app:latest python manage.py test

#deploy:
 # stage: deploy
  #script:
   # - docker pull registry.gitlab.com/<namespace>/<project-name>:latest
    #- docker run -it -d -p 8000:8000 registry.gitlab.com/<namespace>/<project-name>:latest
