image: roffe/kubectl


services:
  - docker:dind


# $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#before_script:
 # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  #- echo $CI_REGISTRY_USER
  #- echo $CI_REGISTRY
stages:
  - build
  - test
  - deploy
# This section describes what shall be done to build and test the project.
#build-and-test:
 # tags:
  #  - docker-build
  #stage: build
  #before_script:
   #   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  #script:
   # - docker build -t registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection .
   # - docker images
   # - docker tag app:latest git.chalmers.se/courses/dit825/2022/group03
 #   - docker push registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection
    #- docker push app:latest
    # - docker run -t app:latest /bin/bash
    
   # - exit

deploy:
  tags: 
    - docker-build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull alpine/k8s
    - docker run alpine/k8s
  script:
    - docker pull registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection
    - docker tag registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection europe-docker.pkg.dev/ornate-bastion-371318/age-detection/app
    - kubectl set image deployment/nginx-1 my-container=europe-docker.pkg.dev/ornate-bastion-371318/age-detection/ap:latest
#deploy:
 # stage: deploy
  #script:
   # - docker pull registry.gitlab.com/<namespace>/<project-name>:latest
    #- docker run -it -d -p 8000:8000 registry.gitlab.com/<namespace>/<project-name>:latest

