image: ubuntu-latest

stages:
  - build
  - test

setup:
  stage: build
  script:
    - python --version
    - cd ./webservice
    - -m pip install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate

unit-test:
  stage: test
  script:
    - python3 manage.py test

