image: docker:latest

services:
  - docker:dind

only:
  push:
    - main
  events:
    - push

stages:
  - build
  - test
  - deploy

build-and-test:
  only:
    - main
  tags:
    - docker-build
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t app:latest .
    - docker images
    - docker tag app:latest registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection
    - docker push registry.git.chalmers.se/courses/dit825/2022/group03/dit825-age-detection
    
deploy:
  only:
    - main
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  tags: 
    - docker-build
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CI_DEPLOY_AGENT
    - kubectl get pods
    - kubectl apply -f ./kubernetes/deployement.yaml


