image: docker:20

services:
  - docker:20-dind

stages:
  - build
  - test
  - deploy

build-and-push:
  only:
    - main
  tags:
    - docker-build
  stage: build
  variables:
    DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$DOCKER_TAG -f docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_TAG
    - >
        if [ "$CI_COMMIT_REF_NAME" == "main" ] ; then
          docker image tag $CI_REGISTRY_IMAGE:$DOCKER_TAG $CI_REGISTRY_IMAGE:latest
          docker push $CI_REGISTRY_IMAGE:latest
        fi



