image: ubuntu-latest

stages:
  - build
  - test

setup:
  stage: build
  script:
    - python --version
    - cd ./webservice
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate

unit-test:
  stage: test
  script:
    - python manage.py test

