image: docker:latest

services:
  - docker:dind
# $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
before_script:
  - docker login git.chalmers -u $CI_REGISTRY_USER -p $CI_USER_TOKEN
  - echo $CI_REGISTRY_USER
  - ECHO $CI_REGISTRY
stages:
  - build
  - test
  - deploy
# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  script:
    - docker build -t app:latest .
    - docker images
    - docker push app:latest
    - docker push app

# This section describes what shall be done to deploy artefacts from the project.
test:
  tags:
    - docker-build
  stage: test
  script:
    - docker pull app:latest
    - docker run -t app:latest python manage.py test


#deploy:
 # stage: deploy
  #script:
   # - docker pull registry.gitlab.com/<namespace>/<project-name>:latest
    #- docker run -it -d -p 8000:8000 registry.gitlab.com/<namespace>/<project-name>:latest
