
image: ubuntu-latest

on:
  push:
    branches:
      - main

stages:
  - build
  - test

setup:
  stage: build
  tags: docker
  script:
    - 'echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
    - sudo apt-get install python3
    - sudo python --version
    - cd ./webservice
    - sudo pip3 install -r requirements.txt
    - sudo python3 manage.py makemigrations
    - sudo python3 manage.py migrate

unit-test:
  stage: test
  tags: docker
  script:
    - sudo python3 manage.py test

