image: ubuntu-latest
   

before_script:
  - echo "$USER"
  - echo $ROOT_PASSWORD | sudo -S sleep 1 && sudo apt-get update
stages:
  - build
  - test

setup:
  stage: build
  script:
    - echo $ROOT_PASSWORD | sudo -S sleep 1 && sudo su - chmod -R a+rwx /var/lib/dpkg/lock-frontend
    - sudo apt-get install python3
    - sudo python --version
    - cd ./webservice
    - sudo pip3 install -r requirements.txt
    - sudo python3 manage.py makemigrations
    - sudo python3 manage.py migrate

unit-test:
  stage: test
  script:
    - sudo python3 manage.py test

