#version: '3.9.0'
#
#services:
#    app:
#        build: .
#        volumes:
#            - .:/django
#        ports:
#            - 8000:8000
#        image: app:django
#        container_name: django_container
#        command: python ./webservice/manage.py runserver 0.0.0.0:8000