version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./webservice:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ""
    command: celery -A main worker -l info
    volumes:
      - ./webservice:/app
    depends_on:
      - db
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


volumes:
  postgres_data:
  redis_data:



