apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "age-detection-helm-chart.fullname" . }}
data:
  REDIS_URL: {{ default (printf "redis://%s-redis-master:%s" .Release.Name  .Values.redis.port) .Values.redis.host | quote }}
  POSTGRES_HOST: {{ default (printf "%s-postgresql" .Release.Name) .Values.postgresql.host | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword }}
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  SQL_ENGINE: "django.db.backends.postgresql"
