apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "age-detection-helm-chart.fullname" . }}-storage-pvc
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    {{- include "age-detection-helm-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
