apiVersion: v1
kind: Service
metadata:
  name: age-app
  namespace: age-detection
  labels:
    app: age-app
spec:
  selector:
    app: age-app
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - port: 8000 
    targetPort: 8000